### ISSUE TITLE
Tracker for cartography issues 

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#47]
Right now I know of these cartography issues:

- [x] Fix highway sprites (like interstate icons in the US) not showing up on the map
- [ ] Fix the missing pedestrian_polygon sprite (see: https://github.com/ellenhp/headway/pull/45#issuecomment-1144710951)
- [ ] Identify which openmaptiles layer contains park information and change the style to point to the correct layer (see: https://github.com/ellenhp/headway/pull/45#issuecomment-1144710951)

But there may be others.

**Comment by ellenhp** [comment]
Fixed the cartography issues in #104, it ended up being a sprite set that was incomplete.
