### ISSUE TITLE
Tracker: Support full-planet installation

### ISSUE THREAD

**Issue by ellenhp** [headwaymaps/headway#79]
For a long time I didn't think I wanted to support the full planet use-case but the fact of the matter is that's what everyone wants, and I think it would be really exciting for people and maybe hopefully convince some folks to help me work on the frontend. :)

- [x] Make sure everything is usable with large areas (see: #78 maybe others)
- [ ] Add timeouts to prevent queries of death, especially to Valhalla.
- [ ] Rate limit requests to geospatial services in nginx based on IP address to prevent people from easily using us for batch queries.

Also consider switching to Pelias? I don't want to cause a bunch of churn but it will be extremely expensive to run a full planet installation of nominatim, and imports are very slow. Plus we currently store about 2x as much geocoding data as we really need to since we have two geocoders. Pelias has search & autocomplete, and a places API that could replace nominatim.

**Comment by ellenhp** [comment]
Switched to Pelias and fixed #78

**Comment by ellenhp** [comment]
After seeing the kind of latency and availability problems that this service has I'm not sure we have to worry about batch queries. Valhalla config could probably be improved though, it's chewing through CPU resources like nobody's business.
